title: WSCLA 28
logo: false
email: TBA
description: Workshop on Structure and Constituency in Languages of the Americas
show_downloads: false
google_analytics: false
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar:
  - name: Call for papers
    link: /call
  - name: Program
    link: /program
  - name: Contact
    link: /contact

  github: [metadata]
  
