title: WSCLA 28
logo: false
email: *TBA*
description: 28th Workshop on Structure and Constituency in Languages of the Americas
show_downloads: false
google_analytics: false
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

sidebar:
  - name: Call for papers
  - link: https://wscla28.github.io/call

github: [metadata]
