title: WSCLA 28
logo: false
description: Workshop on Structure and Constituency in Languages of the Americas
email: wscla28@gmail.com
show_downloads: false
google_analytics: false
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

sidebar:
  - name: Call for papers
    link: /call

github: [metadata]
  
