title: WSCLA 28
logo: false
email: *TBA*
description: Workshop on Structure and Constituency in Languages of the Americas
show_downloads: false
google_analytics: false
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
